"""update session schema

Revision ID: 1063a8e6d205
Revises: a5918fe8ccab
Create Date: 2026-07-23 20:46:04.388304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1063a8e6d205'
down_revision: Union[str, Sequence[str], None] = 'a5918fe8ccab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('device_type', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_used_at')
    op.drop_column('sessions', 'os')
    op.drop_column('sessions', 'browser')
    op.drop_column('sessions', 'device_type')
    # ### end Alembic commands ###
