"""add reuse_detected to user_sessions

Revision ID: a5918fe8ccab
Revises: 9670150bc3fc
Create Date: 2026-07-23 19:27:36.811948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5918fe8ccab'
down_revision: Union[str, Sequence[str], None] = '9670150bc3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('reuse_detected', sa.Boolean(), nullable=False , server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'reuse_detected')
    # ### end Alembic commands ###
